# Generated by Django 5.1.2 on 2024-10-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Quality', models.CharField(blank=True, max_length=100, null=True)),
                ('MRP', models.IntegerField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, max_length=500, null=True)),
                ('Orgin', models.CharField(blank=True, max_length=100, null=True)),
                ('Manufacture', models.CharField(blank=True, max_length=100, null=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='product_images')),
            ],
        ),
    ]
