# Generated by Django 5.1.2 on 2024-10-25 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0003_contact_db'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_Db',
        ),
    ]
