# Generated by Django 5.1.2 on 2024-11-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_cart_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Place', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.TextField(blank=True, max_length=500, null=True)),
                ('Mobile_Number', models.IntegerField(blank=True, null=True)),
                ('Zip', models.IntegerField(blank=True, null=True)),
                ('Total_Price', models.IntegerField(blank=True, null=True)),
                ('Messages', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
