# Generated by Django 5.1.2 on 2024-11-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_remove_checkout_db_shipping_amt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_db',
            name='Prod_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Cart Images'),
        ),
    ]
